    name: SteakIt
    main: himbeer\steak\main
    version: 2.0.1
    api: 1.12.0
    
    commands:
        steak:
            description: Gives some Steak to you.
        teststeaks:
            description: Tests how many steaks are set in config.
