name: SteakIt
main: himbeer\steak\main
version: 4.0.1
api: [1.14.0, 2.0.0, 3.0.0, 3.0.0-ALPHA1]

commands:
    steak:
        description: "Gives some Steak to you."
        usage: "/steak [steak|hunger|both]"
        permission: steakit.steak

permissions:
    steakit.steak:
        description: "Main permission for SteakIt"
        default: true
