    name: steak
    main: feed\main
    version: 1.0.0
    api: 1.12.0
    
    commands:
    steak:
      description: Give Steak
      permission: steak.command
      
    permissions:
      steak.command:
      description: "Give Steak"
      default: op
    
    
