#     _____ _             _    _____ _   
#    / ____| |           | |  |_   _| |  
#   | (___ | |_ ___  __ _| | __ | | | |_ 
#    \___ \| __/ _ \/ _` | |/ / | | | __|
#    ____) | ||  __/ (_| |   < _| |_| |_ 
#   |_____/ \__\___|\__,_|_|\_\_____|\__|
# SteakIt configuration file:
# 
# Number of steaks to give to a player:
steaks: 10
steak_msg: "You got 10 free steak!"
console_msg: "The console isn't hungry!"
